# Worksheet 0 - A Tutorial and Assessment on Python and **NumPy**

**Task - 1:**
Create a Python program that converts between different units of measurement.

In [ ]:
def convert():

  """
  Converts between different units of measurement (Length, Weight, Volume).

  The user selects a conversion type, choose the unit, input a value, and the function performs the conversion

  Returns:
  str: The converted value as a string.
  """
  print("Choose conversion type:")
  print("1. Length (meters <-> feet)")
  print("2. Weight (kilograms <-> pounds)")
  print("3. Volume (liters <-> gallons)")


  try:
    choice = int(input("Enter 1,2,or 3:"))

    if choice == 1:
      unit = input("Enter unit to convert from (m for meters, ft for feet):").lower()
      if unit not in ['m','ft']:
        return "Invalid data."

    elif choice == 2:
      unit = input("Enter unit to convert from (kg for kilograms, lbs for pounds):").lower()
      if unit not in ['kg','lbs']:
        return "Invalid data."


    elif choice == 3:
      unit = input("Enter unit to convert from (l for liters, gal for gallons):").lower()
      if unit not in ['l','gal']:
        return "Invalid data."

    else:
      return "Invalid choice."


    value = float(input("Enter value to convert:"))
    conversion = {
        'm':(value * 3.28084,'feet'),
        'ft':(value / 3.28084,'meters'),
        'kg':(value * 2.20462, 'lbs'),
        'lbs':(value / 2.20462, 'kg'),
        'l':(value * 0.264172, 'gallons'),
        'gal':(value / 0.264172, 'liters')
    }
    result,converted_unit = conversion[unit]
    return f"{value} {unit} ={result:.2f} {converted_unit}"
  except ValueError:
    return "Invalid input. Please enter a numerical value"

print(convert())

Choose conversion type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter 1,2,or 3:1
Enter unit to convert from (m for meters, ft for feet):m
Enter value to convert:5
5.0 m =16.40 feet


**Task - 2:**
Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def calculate_sum(numbers):
  """
  Return the sum of a list of number.

  parameters: A list of numeric values.

  return: The sum of the numbers.
  """
  return sum(numbers)

def find_average(numbers):
  """
  Return the average of a list of numbers.

  parameters: A list of numeric values.

  return: The average of the numbers.
  """
  return sum(numbers) / len(numbers)

def find_maximum(numbers):
  """
  Return the maximum of a list of numbers.

  parameters: A list of numeric values.

  return: The maximum of the numbers.
  """
  return max(numbers)

def find_minimum(numbers):
  """
  Return the minimum of a list of numbers.

  parameters: A list of numeric values.

  return: The minimum of the numbers.
  """
  return min(numbers)


def main():
  print("Select an operation:")
  print("1. Calculate the sum")
  print("2. Find the average")
  print("3. Find the maximum")
  print("4. Find the minimum")


  try:
    operation = int(input("Enter the operation number: "))
    if operation not in [1,2,3,4]:
      print("Invalid operation number.")

    numbers_input = input("Enter List of number")
    numbers =list(map(float,numbers_input.split()))

    if operation == 1:
      print("The sum of the numbers is:", calculate_sum(numbers))
    elif operation == 2:
      print("The average of the numbers is:", find_average(numbers))
    elif operation == 3:
      print("The maximum of the numbers is:", find_maximum(numbers))
    elif operation == 4:
      print("The minimum of the numbers is:", find_minimum(numbers))
  except ValueError:
    print("Invalid input. Please enter a list of numbers.")

if __name__ == "__main__":
  main()

Select an operation:
1. Calculate the sum
2. Find the average
3. Find the maximum
4. Find the minimum
Enter the operation number: 1
Enter List of number1 2 3 4 5 6 
The sum of the numbers is: 21.0


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.




In [ ]:
def extract_every_other(lst):
  return lst[::2]

list1=[1,2,3,4,5,6]
print(" Extract Every Other Element: ", extract_every_other(list1))


1. Extract Every Other Element:  [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [ ]:
def get_sublist(lst,start,end):
  return lst[start:end+1]

list2=[1,2,3,4,5,6]
print("Slice a Sublist: ", get_sublist(list2,2,4))

2. Slice a Sublist:  [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

In [ ]:
def reverse_list(lst):
  return lst[::-1]

list3 = [1,2,3,4,5]
print(" Reverse List.", reverse_list(list3))

3. Reverse List. [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [ ]:
def remove_first_last(lst):
  return lst[1:-1]

list4 = [1,2,3,4,5]
print(" Remove First and Last: ", remove_first_last(list4))

4. Remove First and Last:  [2, 3, 4]


5. Get the First n Elements:

In [ ]:
def get_first_n(lst,n):
  return lst[:n]

list5 = [1,2,3,4,5]
print(" Get First n Elements:", get_first_n(list5,3))

5. Get First n Elements: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(lst,n):
  return lst[-n:] if n>0 else[]

list6 = [1,2,3,4,5]
print("Extract Elements from the End:", get_last_n(list6,2))

6. Extract Elements from the End: [4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [ ]:
def reverse_skip(lst):
  return lst[-2::-2]

list7 = [1,2,3,4,5,6]
print("Extract Elements in Reverse Order:", reverse_skip(list7))

7. Extract Elements in Reverse Order: [5, 3, 1]


**4.3 Exercise on Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [ ]:
def flatten(lst):
  flattened_list = []
  for sublist in lst:
    for item in sublist:
      flattened_list.append(item)
  return flattened_list

input_list = [[1,2],[3,4],[5]]
single_list = flatten(input_list)
print("Flattened List:", single_list)

Flattened List: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_elements(lst,indices):
  for index in indices:
    lst = lst[index]
  return lst
list2 = [[1,2,3],[4,5,6],[7,8,9]]
print(" Access Nested Element:",access_nested_elements(list2,[1,2]))

2. Access Nested Element: 6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
def sum_nested(lst):
  total =0
  for item in lst:
    if isinstance(item,list):
      total+=sum_nested(item)
    else:
      total+=item
  return total

list3 = [[1,2],[3,[4,5]],6]
print("Sum of All Elements",sum_nested(list3))

3. Sum of All Elements 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

In [ ]:
def remove_element(lst,elem):
  result = []
  for item in lst:
    if type(item) == list:
      new_sublist = remove_element(item,elem)
      if new_sublist:
        result.append(new_sublist)
    elif item != elem:
      result.append(item)
  return result

input_list = [[1,2], [3,2],[4,5]]
element =2
result = remove_element(input_list,element)
print("Remove Specific Element:", result )

4. Remove Specific Element: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [ ]:
def find_max(lst):
  max_val = float('-inf')
  for item in lst:
    if isinstance(item,list):
      max_val = max(max_val,find_max(item))
    else:
      max_val = max(max_val,item)
  return max_val

input_list = [[1,2],[3,[4,5]],6]
max_value = find_max(input_list)
print(f"Maximum element: {max_value}")

Maximum element: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
def count_occurrences(lst,elem):
  count =0
  for item in lst:
    if isinstance(item,list):
      count+= count_occurrences(item,elem)
    elif item == elem:
      count+=1
  return count

list6=[[1,2],[2,3],[2,4]]
print("6 Count Occurences:", count_occurrences(list6,2))


6 Count Occurences: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [ ]:
def deep_flatten(lst):
  flat_list = []
  for item in lst:
    if isinstance(item,list):
      flat_list.extend(deep_flatten(item))
    else:
      flat_list.append(item)
  return flat_list

list7 = [[[1,2],[3,4]],[[5,6],[7,8]]]
print("Deep Flatten List:", deep_flatten(list7))

Deep Flatten List: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

In [ ]:
def average_nested(lst):
  flat_lst = deep_flatten(lst)
  return sum(flat_lst) / len(flat_lst)

list8 = [[1,2],[3,4],[5,6]]
print("Nested List Average:",average_nested(list8))

Nested List Average: 3.5


**Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [9]:
import numpy as np

empty_arr = np.empty((2,2))
print("Empty Array (2*2):\n", empty_arr)

Empty Array (2*2):
 [[2.0165116e-316 0.0000000e+000]
 [1.5810101e-322 5.3325770e-317]]





2. Initialize an all one array with size 4X2.

In [10]:
ones_arr = np.ones((4,2))
print("All Ones Array (4*2):\n", ones_arr)

All Ones Array (4*2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [12]:
fill_value_array = np.full((3,3),7)
print("Array Filled with 7 (3*3):\n",fill_value_array)

Array Filled with 7 (3*3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [13]:
given_array = np.array([[1,2],[3,4]])
zeros_like_array = np.zeros_like(given_array)
print("Array of Zeros Like Given Array:\n",zeros_like_array)

Array of Zeros Like Given Array:
 [[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [14]:
one_like_array = np.ones_like(given_array)
print("Array of Ones Like Given Array:\n",one_like_array)

Array of Ones Like Given Array:
 [[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [15]:
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("One Numpy Array from List:\n",numpy_array)

One Numpy Array from List:
 [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [17]:
array_10_49 = np.arange(10,50)
print("Value from 10 to 50:\n",array_10_49)

Value from 10 to 50:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [21]:
matrix_ = np.arange(9)
matrix_3 = matrix_.reshape(3,3)
print(" 3*3 matrix with values from 0 to 8:\n",matrix_3)

 3*3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [23]:
identity_matrix = np.eye(3, dtype=int)
print("3*3 Identity matrix:\n",identity_matrix)


3*3 Identity matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [28]:
random_array= np.random.random(30)
mean_value = random_array.mean()
print("Mean of Random array(size 30):\n",mean_value)

Mean of Random array(size 30):
 0.5458563032340967


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [31]:
random_matrix = np.random.random((10,10))
print("Random Matrix (10*10):\n",random_matrix)
min_value = random_matrix.min()
max_value = random_matrix.max()

print("Minimum Value:",min_value)
print("Maximum Value:",max_value)

Random Matrix (10*10):
 [[0.76683474 0.74372689 0.69669158 0.41627943 0.13570376 0.21375531
  0.92815884 0.13976464 0.29298325 0.33195538]
 [0.4188817  0.00940841 0.12975283 0.1966875  0.37322716 0.9074189
  0.95987005 0.98295611 0.00176805 0.40423118]
 [0.63474326 0.24294561 0.07246039 0.99507952 0.88132014 0.81444783
  0.5674079  0.69454402 0.6976864  0.28757319]
 [0.95143725 0.68333279 0.16041633 0.15899399 0.22007767 0.70840838
  0.93839659 0.12826946 0.35320526 0.85036463]
 [0.339198   0.52703112 0.47981081 0.16588933 0.95476463 0.48083101
  0.99613358 0.10158363 0.8100754  0.37606508]
 [0.54153728 0.14705224 0.29082552 0.24463084 0.03364182 0.90837326
  0.74111145 0.40833012 0.30034684 0.58913513]
 [0.9907397  0.5940559  0.19703587 0.01071897 0.88273523 0.1649515
  0.03566152 0.46437298 0.42488335 0.90344111]
 [0.71370896 0.49151719 0.4276983  0.41704791 0.89164461 0.45072084
  0.2950083  0.18605003 0.96912627 0.41124293]
 [0.50077797 0.12973803 0.86471628 0.3441652  0.83982079 0

6. Create a zero array of size 10 and replace 5th element with 1.

In [34]:
zero_array = np.zeros(10 ,dtype=int)
zero_array[4] = 1
print("Replacing 5th element with 1: \n",zero_array)

Replacing 5th element with 1: 
 [0 0 0 0 1 0 0 0 0 0]


7. Reverse an array arr = [1,2,0,0,4,0].

In [35]:
arr =np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("Reversed array is:\n",reversed_arr)

Reversed array is:
 [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [37]:
border_array = np.ones((5,5),dtype=int)
border_array[1:-1, 1:-1] =0

print("2d array witj 1 on border and 0 inside:\n",border_array)

2d array witj 1 on border and 0 inside:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [39]:
checkboard = np.zeros((8,8),dtype=int)
checkboard[1::2, ::2] =1
checkboard[::2, 1::2] =1
print("8*8 CheckBoard Pattern:\n",checkboard)

8*8 CheckBoard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and

y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and

w = np.array([11,12]);

1. Add the two array.

In [43]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add_xy = np.add(x,y)
print("Addition of two array x and y is:\n ",add_xy)


Addition of two array x and y is:
  [[ 6  8]
 [10 13]]


2. Subtract the two array.

In [44]:
sub_xy = np.subtract(x,y)
print("Subtraction of two array x and y is:\n ",sub_xy)

Subtraction of two array x and y is:
  [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [45]:
multiply_x = x*2
print("Multiplying of x by 2: \n",multiply_x)

Multiplying of x by 2: 
 [[ 2  4]
 [ 6 10]]


4. Find the square of each element of the array.

In [46]:
square_x = np.square(x)
print("Square of each element in x:\n",square_x)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [48]:
dot_vw = np.dot(v,w)
dot_xv = np.dot(x,v)
dot_xy = np.dot(x,y)

print("Dot Products:")
print("Dot product of v and w:",dot_vw)
print("Dot products of x and v:", dot_xv)
print("Dot products of x and y:",dot_xy)

Dot Products:
Dot product of v and w: 219
Dot products of x and v: [29 77]
Dot products of x and y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [56]:
concat_xy = np.concatenate((x,y),axis =0)
print("Concatenate of x and y along rows: \n",concat_xy)

concat_vw = np.vstack((v,w))
print("Concatenate of v and w along columns: \n",concat_vw)

Concatenate of x and y along rows: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate of v and w along columns: 
 [[ 9 10]
 [11 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [60]:
try:
  concat_xv = np.concatenate((x,v), axis=0)
  print("Concatenate of x and v: \n",concat_xv)
except ValueError as e:
  print("Error in concatenating  x and v:")
  print(e)

Error in concatenating  x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations:**

• For the following arrays:

A = np.array([[3,4],[7,8]]) and

 B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)ᵀ = BᵀAᵀ

In [68]:
# 1. Prove A.A−1 = I.

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

from numpy import linalg

inverse_A = np.linalg.inv(A)
result1 = np.dot(A, inverse_A)
print(f"Result of A.A−1:\n{np.round(result1)}")

# 2. Prove AB ̸= BA.

prod_AB = np.dot(A, B)
prod_BA = np.dot(B, A)

check = np.array_equal(A, B)
print("\n")
if check == True:
  print("AB = BA")
else:
  print("AB != BA")


# 3. Prove (AB)T = BTAT

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

prod_BTAT = np.dot(transpose_B, transpose_A)
transpose_AB = np.transpose(prod_AB)

check1 = np.array_equal(transpose_AB, prod_BTAT)
print("\n")
if check1 == True:
  print("(AB)ᵀ = Bᵀ.Aᵀ")
else:
  print("(AB)ᵀ != Bᵀ.Aᵀ")

Result of A.A−1:
[[1. 0.]
 [0. 1.]]


AB != BA


(AB)ᵀ = Bᵀ.Aᵀ


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9


{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [82]:
A = np.array ([[2,-3,1],
               [1,-1,2],
               [3,1,-1]])

print("Cofficinet of Matrix A",A)

B = np.array([-1,-3,9])
print("Cofficinet of Matrix B",B)


A_inv = np.linalg.inv(A)
x_solution = np.dot(A_inv,B ).astype(int)

print("Solution for linear Equations:")
print("  x=", x_solution[0], )
print("  y=", x_solution[1])
print("  z=", x_solution[2])


Cofficinet of Matrix A [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Cofficinet of Matrix B [-1 -3  9]
Solution for linear Equations:
  x= 2
  y= 1
  z= -2


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [83]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

inv_A = np.linalg.inv(A)
X = np.dot(inv_A, B)
print("Solution vector X using np.linalg.inv function:")
print(X)

Solution vector X using np.linalg.inv function:
[ 2.  1. -2.]


**Experiment: How Fast is Numpy?**

1. Element-wise Addition:


• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [88]:
import time

list1 = list(range(1,1_000_001))
list2 = list(range(1_000_001, 2_000_001))

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_time = [a+b for a,b in zip(list1,list2)]
end_time = time.time()
list_time = end_time-start_time
print(f"The time taken for element-wise addisition using Python lis:{list_time:.6f}seconds")



start_time = time.time()
result_time = array1 + array2
end_time = time.time()
array_time = end_time-start_time
print(f"The time taken for element-wise addisition using Numpy arrays:{array_time:.6f}seconds")




The time taken for element-wise addisition ising Python lis:0.101266seconds
The time taken for element-wise addisition ising Numpy arrays:0.018124seconds


2. Element-wise Multiplication


• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [93]:
list1 = list(range(1,1_000_001))
list2 = list(range(1_000_001, 2_000_001))


array1 = np.array(list1)
array2 = np.array(list2)


start_time = time.time()
result_time = [a*b for a,b in zip(list1,list2)]
end_time = time.time()
list_time = end_time-start_time
print(f"The time taken for element-wise multiplication using Python lis:{list_time:.6f}seconds")


start_time = time.time()
result_time = array1 * array2
end_time = time.time()
array_time = end_time-start_time
print(f"The time taken for element-wise multiplication using Numpy arrays:{array_time:.6f}seconds")







The time taken for element-wise multiplication using Python lis:0.061251seconds
The time taken for element-wise multiplication using Numpy arrays:0.012839seconds


3. Dot Product


• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [92]:

list1 = list(range(1,1_000_001))
list2 = list(range(1_000_001, 2_000_001))


array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
dot_product_list = sum(a*b for a,b in zip(list1,list2))
end_time = time.time()
list_time = end_time-start_time
print(f"The time taken for element-wise dot product using Python lis:{list_time:.6f}seconds")


start_time = time.time()
dot_product_array = np.dot(array1 , array2)
end_time = time.time()
array_time = end_time-start_time
print(f"The time taken for element-wise dot product using Numpy arrays:{array_time:.6f}seconds")





The time taken for element-wise dot product using Python lis:0.079739seconds
The time taken for element-wise dot product using Numpy arrays:0.001834seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [98]:
size = 1000


matrix1 = np.random.rand(size, size)
matrix2 = np.random.rand(size, size)

matrix1_list = matrix1.tolist()
matrix2_list = matrix2.tolist()

def matrix_mult(A,B):
  result = []
  for row in A:
    new_row = []
    for col in zip(*B):
      new_row.append(sum(a*b for a,b in zip(row,col)))
    result.append(new_row)
  return result

start_time = time.time()
result_list = matrix_mult(matrix1_list,matrix2_list);
end_time = time.time()
print(f"The time taken for matrix multiplication using python list  :{array_time:.6f}seconds")

start_time = time.time()
result_matrix = np.dot(matrix1, matrix2)
end_time = time.time()
array_time = end_time-start_time
print(f"The time taken for matrix multiplication using Numpy arrays:{array_time:.6f}seconds")




The time taken for matrix multiplication using python list  :0.068233seconds
The time taken for matrix multiplication using Numpy arrays:0.065667seconds
